### ISSUE TITLE
Tests for raw data operations of the DAC driver

### ISSUE THREAD

**Issue by lumip** [qutech/special-measure.pulsecontrol#5]
Tests should work like the Basic Hardware Driver Test (see issue #3 in qc-toolkit repository) by uploading waveforms, reading them via DAC and evaluating expected and mesaured signals.

The tests cover downsampling and repetitive signal averaging.

**Comment by lumip** [comment]
Data generation functions are written. Correct configuration of the DAC driver as well as evaluation of the results remain.

**Comment by pbethke** [comment]
we should think about what type of pulse is suitable for testing downsampling, etc.

**Comment by lumip** [comment]
We have already implemented a very simple test pulse and expected downsampled values. However, a more elaborate pulse would like pose a better test. Ideally, a variety of different pulses should be used for each readout operation. I will create separate issues for this.
On the other hand, maybe we should wait with implementing to many test pulses before the pulse definition and generation components of the software are revised or else we would likely have to adapt all tests afterwards.

**Comment by lumip** [comment]
I'll close this ticket, since it has been split up into more detailed ones.
